# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    
    encoders:
        UsuariosBundle\Entity\User: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            #memory: ~
                #memory:
                    #ASÍ ESTABA INICIALMENTE
                        #users:
                                #ryan:
                                    #password: ryanpass
                                    #roles: 'ROLE_USER'
                                #admin:
                                    #password: 1234
                                    #roles: 'ROLE_ADMIN'
                    memory: ~
        my_db_provider:
                        entity:
                            class: UsuariosBundle:User
                            property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        admin:
            #anonymous: ~
#            #ASÍ ESTABA INICIALMENTE
#            pattern: ^/admin
#            http_basic: ~
            pattern: ^/admin
            anonymous: ~
            provider: my_db_provider
            form_login:
                login_path: login
                check_path: login
                
                #ASÍ ESTABA INICIALMENTE            
#        usuarios:
#            pattern: ^/usuarios
#            anonymous: ~
#            provider: in_memory
#            form_login:
#                    login_path: /usuarios/login
#                    check_path: /usuarios/login
#            logout:
#                path:   /usuarios/logout
#                target: /usuarios

        main:
            anonymous: ~
            
            #provider: in_memory, son todos nuestros usuarios que tenemos definidos arriba en memoria, en este caso admin

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            
            #ASÍ ESTABA INICIALMENTE
#    access_control:
#            - {path: ^/usuarios/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
#            - {path: ^/usuarios, roles: ROLE_ADMIN}
            
            
    access_control:
            - {path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
            - {path: ^/admin, roles: ROLE_ADMIN}